### PR TITLE
Add lockfile for dependabot

### PR DESCRIPTION
**Pull request by justanotherdot**
cc @wooly does this look alright?

### CODE REVIEW

**Comment by justanotherdot** [comment]
ah, I've locked with too high a version of bundler that isn't present in the ci image, will fix.

**Comment by wooly** [comment]
I'm not sure this is required, as dependabot should be parsing the gemspec file already there: https://dependabot.com/ruby/

> Dependabot will propose updates to your Gemfile and/or gemspec, as well as your Gemfile.lock. Alternatively, you can set Dependabot to only make lockfile updates.

**Comment by justanotherdot** [comment]
image

**Comment by wooly** [comment]
Ah sorry, I don't think there's a need to add dependabot here as it wont do anything. I was expecting dependabot to notify us if we had security issues with our gemspec constraints. For example, if we had `gem "bundler",  "> 1.6"` and there was an issue with 1.6.1, it would tell us to change the constraint to "> 1.6.1"

**Comment by justanotherdot** [comment]
There is currently one indirectly proposed for rake on this project https://github.com/kinesisptyltd/activesupport-fiscal_dates/security/dependabot/activesupport-fiscal_dates.gemspec/rake/open

**Comment by wooly** [comment]
Ah I'd be happy in that case for dependabot to open an issue about it but not do anything with the gemspec/gemlock

**Pull request closed without merging**
